### ISSUE TITLE
BIG PROBLEM! Going to the safe green place after death makes your save file obsolete!!

### ISSUE THREAD

**Issue by Gharju** [talesofgames/barkley2_bugs#10]
**Describe the bug**
When dying enough times you go to the green place. The problem is that there is no way out of the green place/the junkyard/cave... So you are stuck! Happened to me twice already while exploring the sewers, where I die constantly.

**Expected behavior**
Remove this spawn point in the demo or make it so that you can return to the sewers.

**Comment by bhroom** [comment]
So this is solely for the demo and is the zone you go to when you die enough times.  I think it's confusing and I'll take it out.
