### ISSUE TITLE
Dying before extending the initial bridge gets you stuck in the sewers!

### ISSUE THREAD

**Issue by Gharju** [talesofgames/barkley2_bugs#11]
**Describe the bug**
I died when I fought the blue container duergar and got spawned in the sewers. But the problem is I had not gone into the sewers before this, so I am stuck on the other side of the unextended bridge near the exit to Tir na nog, with the lewer being on the other side.

**Expected behavior**
Maybe make this bridge have a lewer on each side or something.

**Comment by Smashzone** [comment]
I agree with this, but for the record there are other ways out of the sewers (There's a ladder somewhere on the western side of floor 1, and if you can get past Bass Mother you can get to the L.O.N.G.I.N.U.S clubhouse)

**Comment by Gharju** [comment]
Ok I wasn't able to explore enough of the sewers to find these two other ways out of there, before getting spawned in the green zone. But I still think the originial entrance to sewers should be accessible for players like me, who just wanted to get out of the sewers asap and not have to explore all of it, at that point. I dunno

**Comment by Smashzone** [comment]
nah, that's fine. I was agreeing with you on adding a switch to the other side, just thought you might like to know that there are other ways out. Funnily enough my first playthough I also died to the blue container duergar.

**Comment by bhroom** [comment]
I'm going to leave the ladder on the entire time, there's no point in having it closed.
