### ISSUE TITLE
Booty Daimyo dialogue Bug

### ISSUE THREAD

**Issue by Gharju** [talesofgames/barkley2_bugs#12]
**Describe the bug**
When I talked to Stonewall "Booty Daimyo" Jackson I had bug where instead of the text boxes continuing on popping up as normal, I got stuck on a perpetual dialogue "pause screen". See the dialogue choices I picked below:

**To Reproduce**
1. Talk to Stonewall
2. Pick "Heck yeah!"
3. Pick "Smooth Jazz"
4. Pick "DJ Feudalism"

**Expected behavior**
I expected Stonewall to comment on my sweet name!

**Comment by bhroom** [comment]
this is definitely fixed in the new build
