### ISSUE TITLE
Wilmer's house no gun's crash

### ISSUE THREAD

**Issue by Smashzone** [talesofgames/barkley2_bugs#4]
**Describe the bug**
I used the text skip while clicking (to get though the "item get" info boxes) through the table dialog, and pressed Q afterwards.
it also looks like I had no gun's in my pockets judging by the viewbox (as seen in screenshot)
(edit: I went through both CC and the intro beforehand)

**To Reproduce**
not sure but I was holding space to skip while also clicking

**Screenshots**
![image](https://user-images.githubusercontent.com/51929631/59632611-35d27500-9110-11e9-9330-fb01785b6f3b.png)
(I had pressed "ignore" a couple times before taking the screenshot, sorry)

**Desktop (please complete the following information):**
 - OS: Windows 7

[save2.zip](https://github.com/talesofgames/barkley2_bugs/files/3298654/save2.zip)

**Comment by bhroom** [comment]
I believe Frankie fixed this and it will be live in the next build.
