### ISSUE TITLE
Crashed on start

### ISSUE THREAD

**Issue by TouringBus** [talesofgames/barkley2_bugs#7]
Started up game, instantly got this bug

```

___________________________________________
############################################################################################
FATAL ERROR in Vertex Shader compilation
ShaderName: shader_hue

D3DXCompile failed - result

at gml_Object_oTitle_Other_20
############################################################################################
--------------------------------------------------------------------------------------------
stack frame is
gml_Object_oTitle_Other_20 (line -1)
called from - gml_Object_oTitle_Draw_0 (line -1) - <unknown source line>

```

And it crashed.
 
I am on a fresh install of windows 10, barkley 2 is literally the second application I installed after firefox.

**Comment by bhroom** [comment]
this is a directx issue yeah paperjack? I am assuming we can just leave a link the re readme

**Comment by paperjack93** [comment]
@TouringBus @bhroom 
Indeed I think it is.
Can you please install the latest drivers for your video card, and the latest directx? 
https://www.microsoft.com/en-us/download/details.aspx?id=34429
If the above link doesn't work, try this
https://www.microsoft.com/en-us/download/details.aspx?id=35&44F86079-8679-400C-BFF2-9CA5F2BCBDFC=1

**Comment by paperjack93** [comment]
Will assume its solved

**Comment by TouringBus** [comment]
sorry, had to reset my github login

Drivers are up to date according to nvidia's GEFORCE EXPERIENCE
